// === store/discovery.js ===
/* ===== store/js/discovery.js ===== */
/* ALIN V99 — focused storefront growth layer. No data bootstrap, observer, or competing poll loop. */
(()=>{
  'use strict';
  const FAV_KEY='alin_v99_favorites';
  const state={filters:{kind:'',grade:'',subject:'',teacher:'',min:'',max:'',available:'',badge:'',sort:'recommended'},tables:{},schema:{},timer:null,modalReturnFocus:null};
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const num=v=>Number(v)||0;
  const fmt=v=>new Intl.NumberFormat('ar-IQ').format(num(v));
  const now=()=>Date.now();
  const imageUrl=p=>{try{return p?(typeof mediaUrl==='function'?mediaUrl(p):p):''}catch(_){return p||''}};
  const teacherBy=id=>(db.accounts?.teachers||[]).find(t=>String(t.id)===String(id));
  const statusVisible=s=>!['hidden','inactive','deleted','archived','draft'].includes(String(s||'published'));
  const hasSb=()=>typeof sb!=='undefined'&&!!sb;
  const isDesktop=()=>document.body.classList.contains('store-desktop');
  const isMobile=()=>document.body.classList.contains('store-mobile');
  const orderCounts=()=>{const x={};(db.orders||[]).forEach(o=>x[`${o.kind}:${o.item_id}`]=(x[`${o.kind}:${o.item_id}`]||0)+num(o.qty||1));return x};
  function canonicalItems(){
    const counts=orderCounts();
    const books=(db.booklets||[]).filter(x=>statusVisible(x.status)).map(x=>{
      const t=teacherBy(x.teacher_id)||{};return {kind:'booklet',id:String(x.id),raw:x,title:x.title||'ملزمة',teacher:t.name||'',teacherId:x.teacher_id||'',subject:x.subject||'',grade:x.grade||'',category:'ملازم',price:num(x.price),originalPrice:num(x.original_price),stock:x.stock==null?null:num(x.stock),image:x.cover_path||x.image_path||'',cover:x.cover_path||x.image_path||'',created:x.created_at||'',sold:num(x.sales_count)||counts[`booklet:${x.id}`]||0,badge:x.badge||'',prep:num(x.prep_minutes),dealPrice:num(x.deal_price),dealStart:x.deal_start,dealEnd:x.deal_end,description:x.description||'',status:x.status};
    });
    const products=(db.products||[]).filter(x=>statusVisible(x.status)).map(x=>({kind:x.type||'product',id:String(x.id),raw:x,title:x.name||x.title||'منتج',teacher:x.teacher||'',teacherId:x.teacher_id||'',subject:x.subject||x.category||'',grade:x.grade||'',category:x.category||x.type||'',price:num(x.price),originalPrice:num(x.original_price),stock:x.stock==null?null:num(x.stock),image:x.image_path||x.cover_path||'',cover:x.image_path||x.cover_path||'',created:x.created_at||'',sold:num(x.sales_count)||counts[`${x.type||'product'}:${x.id}`]||counts[`product:${x.id}`]||0,badge:x.badge||'',prep:num(x.prep_minutes),dealPrice:num(x.deal_price),dealStart:x.deal_start,dealEnd:x.deal_end,description:x.description||'',status:x.status}));
    return [...books,...products];
  }
  function activeDeal(x){const t=now(),a=x.dealStart?Date.parse(x.dealStart):0,b=x.dealEnd?Date.parse(x.dealEnd):0;return x.dealPrice>0&&x.dealPrice<x.price&&(!a||a<=t)&&(!b||b>=t)}
  function effectivePrice(x){return activeDeal(x)?x.dealPrice:x.price}
  function stableKey(kind,id){return `${kind}:${id}`}
  function favorites(){
    let rows=[];for(const key of [FAV_KEY,'alin_v98_favorites','alin_v85_favorites','ALIN_FAVORITES']){try{const x=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(x))rows.push(...x.map(v=>typeof v==='string'?v:stableKey(v.kind,v.id)))}catch(_){}}
    rows=[...new Set(rows.map(String).filter(Boolean))];localStorage.setItem(FAV_KEY,JSON.stringify(rows));try{localStorage.setItem('alin_v98_favorites',JSON.stringify(rows))}catch(_){}return rows;
  }
  function canonicalFavoriteItems(){return favorites().map(k=>{const [kind,...id]=k.split(':');return findItem(kind,id.join(':'))}).filter(Boolean)}
  window.v99ShowFavorites=()=>{const rows=canonicalFavoriteItems();modal(`<section class="v99-desktop-favorites"><h2>المفضلة</h2>${rows.length?`<p class="muted">${fmt(rows.length)} مادة محفوظة للعودة إليها بسهولة.</p><div class="v99-rail">${rows.map(miniCard).join('')}</div>`:`<div class="v99-favorites-empty"><span aria-hidden="true">آ</span><h3>مفضلتك جاهزة لاختياراتك</h3><p>احفظ المواد والمنتجات التي تهمك لتجدها هنا في أي وقت.</p><button type="button" data-v99-action="browseProducts">تصفح المنتجات</button></div>`}</section>`)};
  function isFav(x){return favorites().includes(stableKey(x.kind,x.id))}
  window.v99ToggleFavorite=(kind,id)=>{let rows=favorites(),key=stableKey(kind,id);rows=rows.includes(key)?rows.filter(x=>x!==key):[...rows,key];localStorage.setItem(FAV_KEY,JSON.stringify(rows));try{localStorage.setItem('alin_v98_favorites',JSON.stringify(rows))}catch(_){}renderEffectiveStore();updateDesktopHeader();if(typeof toast==='function')toast(rows.includes(key)?'تمت الإضافة إلى المفضلة':'تمت الإزالة من المفضلة')};
  const badges=x=>[
    x.badge,activeDeal(x)?'عرض اليوم':'',x.sold>=5?'الأكثر طلباً':'',x.created&&Date.now()-Date.parse(x.created)<30*864e5?'جديد':'',x.stock!==null&&x.stock>0&&x.stock<=5?'كمية محدودة':''
  ].filter(Boolean);
  function card(x){const out=x.stock!==null&&x.stock<=0,p=effectivePrice(x);return `<article class="v99-product-card" data-v99-item="${esc(stableKey(x.kind,x.id))}">
    <button class="v99-fav" type="button" data-v99-action="favorite" data-kind="${esc(x.kind)}" data-id="${esc(x.id)}" aria-label="المفضلة">${isFav(x)?'♥':'♡'}</button>
    <button class="v99-product-media" type="button" data-v99-action="details" data-kind="${esc(x.kind)}" data-id="${esc(x.id)}" aria-label="عرض تفاصيل ${esc(x.title)}">${x.image?`<img src="${esc(imageUrl(x.image))}" alt="" loading="lazy">`:'<span class="v99-placeholder" aria-hidden="true">آ</span>'}</button>
    <div class="v99-product-body"><div class="v99-badges">${badges(x).map(b=>`<span class="v99-badge ${b==='كمية محدودة'?'stock':''}">${esc(b)}</span>`).join('')}</div>
      <h3><button class="v99-title-button" type="button" data-v99-action="details" data-kind="${esc(x.kind)}" data-id="${esc(x.id)}">${esc(x.title)}</button></h3><p>${esc([x.teacher,x.subject,x.grade].filter(Boolean).join(' • '))}</p>
      <div class="v99-card-meta"><span class="v99-stock ${out?'out':''}">${x.stock===null?'متاح':out?'نافد':`متوفر: ${fmt(x.stock)}`}</span><span>${x.prep?`تجهيز ${fmt(x.prep)} د`:'تجهيز حسب المكتبة'}</span></div>
      <div class="v99-card-price">${fmt(p)} د.ع ${activeDeal(x)?`<del>${fmt(x.price)}</del>`:''}</div>
      <div class="v99-actions"><button class="${out?'v99-alert-action':''}" data-v99-action="cart" data-kind="${esc(x.kind)}" data-id="${esc(x.id)}">${out?'أبلغني':'أضف للسلة'}</button><button class="v99-secondary" data-v99-action="details" data-kind="${esc(x.kind)}" data-id="${esc(x.id)}">التفاصيل</button></div>
    </div></article>`}
  function matches(x){const f=state.filters,q=String($('#searchInput')?.value||'').trim().toLowerCase(),hay=[x.title,x.teacher,x.subject,x.grade,x.category].join(' ').toLowerCase();return (!q||hay.includes(q))&&(!f.kind||x.kind===f.kind||x.category===f.kind)&&(!f.grade||x.grade===f.grade)&&(!f.subject||x.subject===f.subject)&&(!f.teacher||String(x.teacherId)===f.teacher)&&(!f.min||effectivePrice(x)>=num(f.min))&&(!f.max||effectivePrice(x)<=num(f.max))&&(!f.available||(f.available==='yes'?(x.stock===null||x.stock>0):x.stock===0))&&(!f.badge||(f.badge==='deal'?activeDeal(x):badges(x).includes(f.badge)))}
  function sorted(rows){const f=state.filters.sort;return rows.sort((a,b)=>f==='newest'?String(b.created).localeCompare(String(a.created)):f==='best'?b.sold-a.sold:f==='priceAsc'?effectivePrice(a)-effectivePrice(b):f==='priceDesc'?effectivePrice(b)-effectivePrice(a):(activeDeal(b)-activeDeal(a))||(b.sold-a.sold))}
  function options(rows,key,label,value=x=>x[key]){return `<option value="">${label}</option>`+[...new Map(rows.map(x=>[String(value(x)||''),String(value(x)||'')])).values()].filter(Boolean).sort().map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}
  function renderFilters(){const root=$('#v99DiscoveryTools');if(!root)return;const rows=canonicalItems(),teachers=(db.accounts?.teachers||[]).filter(t=>t.status==='active'||!t.status),desktop=isDesktop(),mobile=isMobile();if(desktop||mobile){root.setAttribute('role','dialog');root.setAttribute('aria-modal','true');root.setAttribute('tabindex','-1')}if(desktop)root.setAttribute('aria-labelledby','v99FilterDrawerTitle');if(mobile)root.setAttribute('aria-labelledby','v99MobileFilterDrawerTitle');const drawerHead=desktop?`<div class="v99-drawer-head"><h2 id="v99FilterDrawerTitle">فلترة المنتجات</h2><button type="button" class="v99-drawer-close" data-v99-action="closeDesktopFilters" aria-label="إغلاق لوحة الفلاتر">×</button></div>`:mobile?`<div class="v99-mobile-drawer-head"><h2 id="v99MobileFilterDrawerTitle">فلترة المنتجات</h2><button type="button" class="v99-mobile-drawer-close" data-v99-action="closeMobileFilters" aria-label="إغلاق لوحة الفلاتر">×</button></div>`:`<button class="v99-filter-toggle" type="button" data-v99-action="toggleFilters" aria-expanded="false"><span>تصفية وفرز المنتجات</span><span class="v99-toggle-mark" aria-hidden="true">+</span></button>`;root.innerHTML=`${drawerHead}<div id="v99ActiveFilters" class="v99-active-filters" aria-live="polite"></div><div class="v99-filters" aria-label="عوامل التصفية">
    <label><span>النوع أو القسم</span><select data-filter="kind">${options(rows,'kind','الكل',x=>x.kind)}</select></label><label><span>المرحلة الدراسية</span><select data-filter="grade">${options(rows,'grade','كل المراحل')}</select></label><label><span>المادة</span><select data-filter="subject">${options(rows,'subject','كل المواد')}</select></label><label><span>المدرس</span><select data-filter="teacher"><option value="">كل المدرسين</option>${teachers.map(t=>`<option value="${esc(t.id)}">${esc(t.name)}</option>`).join('')}</select></label>
    <fieldset class="v99-price-range"><legend>نطاق السعر</legend><label><span>من</span><input data-filter="min" type="number" min="0" inputmode="numeric" placeholder="0"></label><label><span>إلى</span><input data-filter="max" type="number" min="0" inputmode="numeric" placeholder="بدون حد"></label></fieldset><label><span>حالة التوفر</span><select data-filter="available"><option value="">الكل</option><option value="yes">متوفر</option><option value="no">نافد</option></select></label><label><span>الشارة أو العرض</span><select data-filter="badge"><option value="">الكل</option><option value="deal">عرض اليوم</option><option>جديد</option><option>الأكثر طلباً</option><option>كمية محدودة</option></select></label><label class="v99-sort-control"><span>ترتيب النتائج</span><select data-filter="sort"><option value="recommended">الموصى بها</option><option value="newest">الأحدث</option><option value="best">الأكثر مبيعاً</option><option value="priceAsc">السعر: الأقل</option><option value="priceDesc">السعر: الأعلى</option></select></label>
    </div><div class="v99-filter-actions"><span class="v99-filter-summary" id="v99FilterSummary"></span><button type="button" class="v99-secondary" data-v99-action="clearFilters">مسح الكل</button></div>`;syncFilterControls();renderFilterChips()}
  function syncFilterControls(){$$('[data-filter]').forEach(el=>{el.value=state.filters[el.dataset.filter]||''})}
  function renderFilterChips(){const root=$('#v99ActiveFilters');if(!root)return;const labels={kind:'النوع',grade:'المرحلة',subject:'المادة',teacher:'المدرس',min:'من',max:'إلى',available:'التوفر',badge:'العرض',sort:'الترتيب'};const rows=Object.entries(state.filters).filter(([k,v])=>v&&!(k==='sort'&&v==='recommended'));const visible=(k,v)=>{if(k==='min'||k==='max')return `${fmt(v)} د.ع`;const control=$(`[data-filter="${k}"]`),option=[...(control?.options||[])].find(o=>o.value===String(v));return option?.textContent?.trim()||String(v)};root.innerHTML=rows.map(([k,v])=>`<button type="button" data-v99-action="removeFilter" data-filter-key="${esc(k)}" aria-label="إزالة فلتر ${esc(labels[k])}">${esc(labels[k])}: ${esc(visible(k,v))} <span aria-hidden="true">×</span></button>`).join('');root.hidden=!rows.length;for(const id of ['v99DesktopFilterCount','v99MobileFilterCount']){const count=$('#'+id);if(count){count.textContent=fmt(rows.length);count.hidden=!rows.length}}}
  function miniCard(x){return `<article class="v99-mini-card"><div class="v99-mini-media">${x.image?`<img src="${esc(imageUrl(x.image))}" alt="">`:'<span class="v99-placeholder">آ</span>'}</div><div class="v99-mini-body"><div class="v99-badges">${badges(x).slice(0,2).map(b=>`<span class="v99-badge">${esc(b)}</span>`).join('')}</div><h3>${esc(x.title)}</h3><p>${esc([x.teacher,x.subject,x.grade].filter(Boolean).join(' • '))}</p><div class="v99-card-price">${fmt(effectivePrice(x))} د.ع</div><button data-v99-action="details" data-kind="${esc(x.kind)}" data-id="${esc(x.id)}">عرض</button></div></article>`}
  function rail(rootId,title,subtitle,rows){const root=$(rootId);if(!root)return;if(!rows.length){root.innerHTML='';return}root.innerHTML=`<div class="v99-section-head"><div><h2>${esc(title)}</h2><small>${esc(subtitle)}</small></div></div><div class="v99-rail">${rows.map(miniCard).join('')}</div>`}
  function renderStage(){const root=$('#v99Personalized');if(!root)return;if(isMobile()){root.replaceChildren();root.hidden=true;return}root.hidden=false;const profile=studentProfile(),grades=[...new Set(canonicalItems().map(x=>x.grade).filter(Boolean))];root.innerHTML=`<div class="v99-stage-strip"><div><h2>مواد تناسب مرحلتك</h2><p>${profile.grade?`نعرض لك اختيارات ${esc(profile.grade)} أولاً.`:'اختر مرحلتك لتحصل على اقتراحات أقرب لدراستك.'}</p></div><select id="v99GradeSelect" aria-label="المرحلة الدراسية"><option value="">كل المراحل</option>${grades.map(g=>`<option ${g===profile.grade?'selected':''}>${esc(g)}</option>`).join('')}</select></div><div id="v99PersonalizedItems" class="v99-rail-root"></div>`}
  function renderDeal(){const root=$('#v99DailyDeals'),x=canonicalItems().filter(activeDeal).sort((a,b)=>(b.price-b.dealPrice)-(a.price-a.dealPrice))[0];if(!root)return;if(!x){root.innerHTML='';return}root.innerHTML=`<article class="v99-deal-feature"><div class="v99-deal-media">${x.image?`<img src="${esc(imageUrl(x.image))}" alt="${esc(x.title)}">`:'<span class="v99-placeholder">ALIN</span>'}</div><div class="v99-deal-copy"><span class="v99-kicker">عرض اليوم</span><h2>${esc(x.title)}</h2><p>${esc([x.teacher,x.subject,x.grade].filter(Boolean).join(' • '))}</p><div class="v99-price">${fmt(x.dealPrice)} د.ع <del>${fmt(x.price)}</del></div><div class="v99-countdown" data-deal-end="${esc(x.dealEnd||'')}"></div><div class="v99-actions"><button data-v99-action="cart" data-kind="${esc(x.kind)}" data-id="${esc(x.id)}">أضف للسلة</button><button class="v99-secondary" data-v99-action="share" data-kind="${esc(x.kind)}" data-id="${esc(x.id)}">مشاركة</button></div></div></article>`;updateCountdowns()}
  function renderRails(){const rows=canonicalItems(),grade=studentProfile().grade;let newest=rows;if(isDesktop()||isMobile()){if(state.filters.badge==='deal')newest=newest.filter(activeDeal);else if(state.filters.kind)newest=newest.filter(x=>x.kind===state.filters.kind)}rail('#v99NewArrivals','وصل حديثاً','أحدث المواد المضافة',newest.filter(x=>x.created).sort((a,b)=>String(b.created).localeCompare(String(a.created))).slice(0,8));const bestBase=isDesktop()||isMobile()?rows.filter(x=>x.kind==='stationery'||x.kind==='gift'):rows;rail('#v99BestSellers','الأكثر طلباً','اختيارات الطلاب الأكثر رواجاً',[...bestBase].sort((a,b)=>b.sold-a.sold).filter(x=>x.sold>0).slice(0,8));renderTeachers();renderBundles();if(grade)rail('#v99PersonalizedItems','حسب مرحلتي','',rows.filter(x=>x.grade===grade).slice(0,8))}
  function visibleAccount(row){
    if(!row||row.deleted_at)return false;
    const status=String(row.status||'active').trim().toLowerCase();
    return !['inactive','disabled','suspended','rejected','deleted','archived'].includes(status);
  }
  function uniqueVisibleCount(rows){
    const seen=new Set();
    for(const row of rows||[]){
      if(!visibleAccount(row))continue;
      const key=String(row.id||row.auth_user_id||row.username||row.phone||row.name||'').trim();
      if(key)seen.add(key);
    }
    return seen.size;
  }
  function renderStoreStats(){
    const booklets=(db.booklets||[]).filter(row=>statusVisible(row.status)&&!row.deleted_at).length;
    const teachers=uniqueVisibleCount(db.accounts?.teachers||[]);
    const libraries=uniqueVisibleCount(db.accounts?.libraries||[]);
    const values={alinStatBooklets:booklets,alinStatTeachers:teachers,alinStatLibraries:libraries};
    for(const [id,value] of Object.entries(values)){
      const node=document.getElementById(id);
      if(node)node.textContent=fmt(value);
    }
    return values;
  }
  function syncDesktopCategoryUI(){if(!isDesktop())return;const active=state.filters.badge==='deal'?'deal':state.filters.kind||'',labels={booklet:['الملازم','كل الملازم المتاحة'],stationery:['القرطاسية','منتجات القرطاسية'],gift:['الهدايا','هدايا مختارة'],deal:['العروض','العروض الفعالة الآن']},copy=labels[active]||['كل المنتجات','الكتالوج الكامل'];$$('[data-v99-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.v99Category===active)));const title=$('#v99CatalogTitle'),kicker=$('#v99CatalogKicker');if(title)title.textContent=copy[0];if(kicker)kicker.textContent=copy[1]}
  function syncMobileCategoryUI(){if(!isMobile())return;const active=state.filters.badge==='deal'?'deal':state.filters.kind||'',labels={booklet:['الملازم','كل الملازم المتاحة'],stationery:['القرطاسية','منتجات القرطاسية'],gift:['الهدايا','هدايا مختارة'],deal:['العروض','العروض الفعالة الآن']},copy=labels[active]||['كل المنتجات','الكتالوج الكامل'];$$('[data-v99-category]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.v99Category===active)));const title=$('#v99MobileCatalogTitle'),kicker=$('#v99MobileCatalogKicker');if(title)title.textContent=copy[0];if(kicker)kicker.textContent=copy[1]}
  function renderEffectiveStore(){
    const grid=$('#storeGrid');
    if(!grid)return;
    const rows=sorted(canonicalItems().filter(matches));
    grid.innerHTML=rows.map(card).join('')||'<div class="v99-empty"><b>لا توجد نتائج مطابقة</b><p>غيّر عوامل التصفية أو امسحها للعودة إلى جميع المواد.</p></div>';
    const summary=$('#v99FilterSummary');
    if(summary)summary.textContent=`${fmt(rows.length)} نتيجة`;
    renderFilterChips();
    syncDesktopCategoryUI();
    syncMobileCategoryUI();
    renderDeal();
    renderRails();
    updateDesktopHeader();
    updateMobileHeader();
    renderStoreStats();
    document.dispatchEvent(new CustomEvent('alin:store-rendered',{detail:{count:rows.length,source:'store-discovery'}}));
    return rows;
  }
  function normalizedStoreType(type){
    const value=String(type||'').trim().toLowerCase();
    if(['gift','gifts'].includes(value))return 'gift';
    if(['stationery','stationary'].includes(value))return 'stationery';
    if(['booklet','booklets'].includes(value))return 'booklet';
    return value;
  }
  function currentStoreItems(){
    const type=normalizedStoreType(db.settings?.storeType||'');
    const rows=canonicalItems();
    if(!type)return rows;
    return rows.filter(item=>normalizedStoreType(item.kind)===type||normalizedStoreType(item.category)===type);
  }
  function renderStore(){
    const signature=`${(db.booklets||[]).length}:${(db.products||[]).length}:${(db.accounts?.teachers||[]).length}`;
    if(state.catalogSignature!==signature){
      state.catalogSignature=signature;
      renderFilters();
      renderStage();
    }
    renderStudentHub();
    return renderEffectiveStore();
  }
  function setStoreType(type,button){
    const value=normalizedStoreType(type)||'booklet';
    db.settings=db.settings||{};
    db.settings.storeType=value;
    state.filters.kind=value;
    state.filters.badge='';
    if(button){
      document.querySelectorAll('[data-v99-category],.store-nav button').forEach(node=>node.classList.remove('active'));
      button.classList.add('active');
    }
    syncFilterControls();
    return renderStore();
  }
  window.storeItems=currentStoreItems;
  window.renderStore=renderStore;
  window.setStoreType=setStoreType;
  window.AlinStorefront=Object.freeze({render:renderStore,items:canonicalItems,currentItems:currentStoreItems,setType:setStoreType,stats:renderStoreStats,openDetails:(kind,id)=>window.v99OpenDetails(kind,id)});
  function publicTeachers(){return (db.accounts?.teachers||[]).filter(t=>t.public_profile===false?false:(t.status==='active'||t.status==='approved'||!t.status))}
  function renderTeachers(){const root=$('#v99TeacherRail'),rows=publicTeachers();if(!root)return;if(isDesktop()||isMobile()){root.innerHTML='';root.hidden=true;return}if(!rows.length){root.innerHTML='';return}root.innerHTML=`<div class="v99-section-head"><div><h2>مدرسون مميزون</h2><small>تعرّف على المدرس وملزماته</small></div></div><div class="v99-rail">${rows.slice(0,10).map(t=>`<article class="v99-teacher-card" data-v99-action="teacher" data-id="${esc(t.id)}"><span class="v99-avatar">${t.avatar_path||t.image_path?`<img src="${esc(imageUrl(t.avatar_path||t.image_path))}" alt="">`:esc((t.name||'آ').slice(0,1))}</span><span><b>${esc(t.name)}</b><small>${esc(t.specialty||t.subject||'مدرس معتمد')}</small></span></article>`).join('')}</div>`}
  function renderBundles(){const root=$('#v99Bundles'),bundles=state.tables.bundles||[],items=state.tables.bundle_items||[];if(!root)return;const active=bundles.filter(b=>b.active!==false&&statusVisible(b.status));if(!active.length){root.innerHTML='';return}root.innerHTML=`<div class="v99-section-head"><div><h2>حزم أوفر</h2><small>مجموعة مواد بسعر واحد</small></div></div><div class="v99-rail">${active.map(b=>{const n=items.filter(i=>String(i.bundle_id)===String(b.id)).length;return `<article class="v99-mini-card"><div class="v99-mini-body"><span class="v99-kicker">حزمة ${fmt(n)} مواد</span><h3>${esc(b.name||b.title)}</h3><p>${esc(b.description||'اختيار متكامل بسعر مخفّض')}</p><div class="v99-card-price">${fmt(b.bundle_price||b.price)} د.ع</div><button data-v99-action="bundle" data-id="${esc(b.id)}">عرض الحزمة</button></div></article>`}).join('')}</div>`}
  function findItem(kind,id){return canonicalItems().find(x=>x.kind===kind&&x.id===String(id))||canonicalItems().find(x=>x.id===String(id))}
  function closeModal(restore=true){const m=$('.v99-modal');if(!m)return;m.remove();document.body.classList.remove('v99-modal-open');if(restore&&state.modalReturnFocus?.isConnected)state.modalReturnFocus.focus();state.modalReturnFocus=null}
  function modal(html){const existing=$('.v99-modal');if(!existing)state.modalReturnFocus=document.activeElement;else existing.remove();const m=document.createElement('div');m.className='v99-modal';m.setAttribute('role','presentation');m.innerHTML=`<div class="v99-modal-card" role="dialog" aria-modal="true" tabindex="-1"><button class="v99-close" type="button" data-v99-action="close" aria-label="إغلاق النافذة">×</button>${html}</div>`;const title=m.querySelector('h2');if(title){title.id='v99DialogTitle';m.querySelector('[role="dialog"]').setAttribute('aria-labelledby','v99DialogTitle')}else m.querySelector('[role="dialog"]').setAttribute('aria-label','نافذة متجر آلين');document.body.appendChild(m);document.body.classList.add('v99-modal-open');requestAnimationFrame(()=>m.querySelector('[role="dialog"]').focus());return m}
  function reviewsFor(x){return (state.tables.product_reviews||[]).filter(r=>r.kind===x.kind&&String(r.item_id)===x.id&&['approved','published'].includes(r.status||'approved'))}
  function relatedItems(x){return canonicalItems().filter(y=>stableKey(y.kind,y.id)!==stableKey(x.kind,x.id)).map(y=>({y,score:(y.subject&&y.subject===x.subject?5:0)+(y.grade&&y.grade===x.grade?4:0)+(y.teacherId&&String(y.teacherId)===String(x.teacherId)?3:0)+(y.category&&y.category===x.category?2:0)})).filter(r=>r.score>0).sort((a,b)=>b.score-a.score).slice(0,6).map(r=>r.y)}
  function relatedDetailHtml(x){const rows=relatedItems(x);return rows.length?`<section class="v99-related"><div class="v99-section-head"><div><h2>مواد مرتبطة</h2><small>اقتراحات من نفس المادة أو المرحلة</small></div></div><div class="v99-rail">${rows.map(miniCard).join('')}</div></section>`:''}
  window.v99OpenDetails=(kind,id)=>{const x=findItem(kind,id);if(!x)return;const rows=reviewsFor(x),avg=rows.length?rows.reduce((a,r)=>a+num(r.rating),0)/rows.length:0,out=x.stock!==null&&x.stock<=0;modal(`<div class="v99-detail"><div class="v99-detail-media">${x.image?`<img src="${esc(imageUrl(x.image))}" alt="${esc(x.title)}">`:'<span class="v99-placeholder">ALIN</span>'}</div><div class="v99-detail-copy"><div class="v99-badges">${badges(x).map(b=>`<span class="v99-badge">${esc(b)}</span>`).join('')}</div><h2>${esc(x.title)}</h2><p>${esc([x.teacher,x.subject,x.grade,x.category].filter(Boolean).join(' • '))}</p><p>${esc(x.description||'مادة مختارة من متجر آلين، راجع التفاصيل وحدد طريقة الاستلام أو التوصيل عند إكمال الطلب.')}</p><div class="v99-price">${fmt(effectivePrice(x))} د.ع ${activeDeal(x)?`<del>${fmt(x.price)}</del>`:''}</div><div class="v99-card-meta"><span>${out?'غير متوفر حالياً':x.stock===null?'متاح للطلب':`المخزون ${fmt(x.stock)}`}</span><span>${x.prep?`تقدير التجهيز ${fmt(x.prep)} دقيقة`:'وقت التجهيز تؤكده المكتبة'}</span></div><div class="v99-notice">يمكنك اختيار الاستلام من المكتبة أو التوصيل عند إكمال الطلب. تبقى الكوبونات الحالية متاحة داخل السلة.</div><div class="v99-qty"><label for="v99DetailQty">الكمية</label><input id="v99DetailQty" type="number" min="1" max="99" value="1"></div><div class="v99-actions">${out?`<button data-v99-action="stockForm" data-kind="${esc(x.kind)}" data-id="${esc(x.id)}">أبلغني عند التوفر</button>`:`<button data-v99-action="cartQty" data-kind="${esc(x.kind)}" data-id="${esc(x.id)}">أضف للسلة</button><button class="v99-secondary" data-v99-action="buy" data-kind="${esc(x.kind)}" data-id="${esc(x.id)}">شراء الآن</button>`}<button class="v99-ghost" data-v99-action="share" data-kind="${esc(x.kind)}" data-id="${esc(x.id)}">مشاركة</button><button class="v99-ghost" data-v99-action="favorite" data-kind="${esc(x.kind)}" data-id="${esc(x.id)}">${isFav(x)?'إزالة من المفضلة':'حفظ بالمفضلة'}</button></div></div></div><section class="v99-reviews"><h3>التقييمات ${rows.length?`— ${avg.toFixed(1)} من 5`:''}</h3>${rows.map(r=>`<div class="row"><div><b>${fmt(r.rating)} / 5</b><small>${esc(r.comment||'')}</small></div></div>`).join('')||'<p class="muted">لا توجد تقييمات منشورة بعد.</p>'}<button data-v99-action="reviewForm" data-kind="${esc(x.kind)}" data-id="${esc(x.id)}">أضف تقييمك</button></section>${relatedDetailHtml(x)}`)};
  async function shareItem(x){const url=new URL(location.href);url.hash='';url.searchParams.set('item',stableKey(x.kind,x.id));const data={title:x.title,text:`${x.title} — ${fmt(effectivePrice(x))} د.ع`,url:url.toString()};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(`${data.text}\n${data.url}`);if(typeof toast==='function')toast('تم نسخ رابط المنتج')}}catch(e){if(e.name!=='AbortError')alert('تعذر نسخ الرابط')}}
  function stockForm(x){modal(`<h2>أبلغني عند التوفر</h2><p>سنحفظ طلب التنبيه في النظام فقط إذا كانت خدمة V99 مفعلة.</p><div class="v99-form"><input id="v99StockContact" placeholder="رقم الهاتف"><button data-v99-action="stockSubmit" data-kind="${esc(x.kind)}" data-id="${esc(x.id)}">حفظ التنبيه</button><div id="v99FormMsg"></div></div>`)}
  async function stockSubmit(x){const el=$('#v99StockContact'),msg=$('#v99FormMsg'),contact=el?.value.trim();if(!contact){msg.innerHTML='<div class="v99-notice error">اكتب رقم الهاتف.</div>';return}if(!state.schema.stock_alerts||!hasSb()){msg.innerHTML='<div class="v99-notice error">خدمة التنبيه تحتاج تطبيق ترحيل V99 على قاعدة البيانات.</div>';return}try{const {error}=await sb.from('stock_alerts').insert({kind:x.kind,item_id:x.id,contact,status:'pending'});if(error)throw error;msg.innerHTML='<div class="v99-notice success">تم تسجيل طلب التنبيه.</div>'}catch(e){msg.innerHTML=`<div class="v99-notice error">لم يتم الحفظ: ${esc(e.message||'راجع إعدادات الخدمة')}</div>`}}
  function reviewForm(x){modal(`<h2>قيّم ${esc(x.title)}</h2><div class="v99-form"><input id="v99ReviewContact" placeholder="رقم الهاتف"><select id="v99ReviewRating"><option value="5">5 — ممتاز</option><option value="4">4 — جيد جداً</option><option value="3">3 — جيد</option><option value="2">2 — مقبول</option><option value="1">1 — ضعيف</option></select><textarea id="v99ReviewComment" placeholder="اكتب رأيك"></textarea><button data-v99-action="reviewSubmit" data-kind="${esc(x.kind)}" data-id="${esc(x.id)}">إرسال للمراجعة</button><div id="v99FormMsg"></div></div>`)}
  async function reviewSubmit(x){const msg=$('#v99FormMsg'),contact=$('#v99ReviewContact')?.value.trim(),rating=num($('#v99ReviewRating')?.value),comment=$('#v99ReviewComment')?.value.trim();if(!contact||!comment){msg.innerHTML='<div class="v99-notice error">أكمل رقم الهاتف والتعليق.</div>';return}if(!state.schema.product_reviews||!hasSb()){msg.innerHTML='<div class="v99-notice error">التقييمات تحتاج تطبيق ترحيل V99.</div>';return}try{const {error}=await sb.from('product_reviews').insert({kind:x.kind,item_id:x.id,student_contact:contact,rating,comment,status:'pending'});if(error)throw error;msg.innerHTML='<div class="v99-notice success">تم إرسال تقييمك للمراجعة قبل النشر.</div>'}catch(e){msg.innerHTML=`<div class="v99-notice error">لم يتم الإرسال: ${esc(e.message||'راجع إعدادات الخدمة')}</div>`}}
  function teacherModal(id){const t=publicTeachers().find(x=>String(x.id)===String(id));if(!t)return;const books=canonicalItems().filter(x=>x.kind==='booklet'&&String(x.teacherId)===String(id));modal(`<div class="v99-detail"><div><span class="v99-avatar">${t.avatar_path||t.image_path?`<img src="${esc(imageUrl(t.avatar_path||t.image_path))}" alt="">`:esc((t.name||'آ').slice(0,1))}</span></div><div class="v99-detail-copy"><span class="v99-kicker">ملف المدرس</span><h2>${esc(t.name)}</h2><p><b>${esc(t.specialty||'مدرس معتمد')}</b></p><p>${esc(t.bio||'مدرس معتمد في منصة آلين.')}</p></div></div><div class="v99-rail">${books.map(miniCard).join('')||'<div class="v99-empty">لا توجد ملازم منشورة حالياً.</div>'}</div>`)}
  function bundleModal(id){const b=(state.tables.bundles||[]).find(x=>String(x.id)===String(id));if(!b)return;const lines=(state.tables.bundle_items||[]).filter(x=>String(x.bundle_id)===String(id)),mapped=lines.map(l=>({...l,item:findItem(l.kind,String(l.item_id))})).filter(x=>x.item);modal(`<h2>${esc(b.name||b.title)}</h2><p>${esc(b.description||'')}</p><div>${mapped.map(x=>`<div class="row"><div><b>${esc(x.item.title)}</b><small>الكمية ${fmt(x.quantity||1)}</small></div><span>${fmt(effectivePrice(x.item))} د.ع</span></div>`).join('')||'<div class="v99-empty">لا توجد عناصر متاحة في هذه الحزمة.</div>'}</div><div class="v99-price">سعر الحزمة: ${fmt(b.bundle_price||b.price)} د.ع</div><button data-v99-action="bundleAdd" data-id="${esc(id)}" ${mapped.length?'':'disabled'}>أضف الحزمة للسلة</button>`)}
  function addBundle(id){const lines=(state.tables.bundle_items||[]).filter(x=>String(x.bundle_id)===String(id));lines.forEach(l=>{for(let i=0;i<Math.max(1,num(l.quantity));i++)if(typeof addToCart==='function')addToCart(l.kind,String(l.item_id))});updateDesktopHeader();if(typeof toast==='function')toast('أضيفت عناصر الحزمة المتاحة إلى السلة')}
  function studentProfile(){try{return JSON.parse(localStorage.getItem('alin_v99_student_profile')||'{}')}catch(_){return{}}}
  function updateDesktopHeader(){if(!isDesktop())return;const favCount=canonicalFavoriteItems().length,fav=$('#v99DesktopFavoriteCount');if(fav){fav.textContent=fmt(favCount);fav.hidden=!favCount}const cartCount=Array.isArray(cart)?cart.reduce((a,x)=>a+Math.max(1,num(x.qty)),0):0,cartBadge=$('#desktopCartCount');if(cartBadge){cartBadge.textContent=fmt(cartCount);cartBadge.hidden=!cartCount}let s=null;try{s=typeof currentStudent==='function'?currentStudent():null}catch(_){}const btn=$('#studentAuthBtn'),status=$('#studentAuthStatus');if(btn)btn.innerHTML=`<span class="desktop-account-icon" aria-hidden="true"></span><small>${esc(s?.name||'تسجيل الدخول')}</small>`;if(status)status.textContent=s?`مرحباً ${s.name}`:'التسجيل اختياري'}
  function updateMobileHeader(){if(!isMobile())return;const favCount=canonicalFavoriteItems().length,fav=$('#mobileFavoriteCount');if(fav){fav.textContent=fmt(favCount);fav.hidden=!favCount}const cartCount=Array.isArray(cart)?cart.reduce((a,x)=>a+Math.max(1,num(x.qty)),0):0,cartBadge=$('#mobileBottomCartCount')||$('#mobileCartCount');if(cartBadge){cartBadge.textContent=fmt(cartCount);cartBadge.hidden=!cartCount}let s=null;try{s=typeof currentStudent==='function'?currentStudent():null}catch(_){}const btn=$('#studentAuthBtn'),status=$('#studentAuthStatus');if(btn)btn.innerHTML=`<span class="mobile-account-icon" aria-hidden="true"></span><small>${esc(s?.name||'الحساب')}</small>`;if(status)status.textContent=s?`مرحباً ${s.name}`:'التسجيل اختياري'}
  async function saveGrade(grade){const p={...studentProfile(),grade};try{const s=typeof currentStudent==='function'?currentStudent():null;if(s){p.phone=s.phone;p.name=s.name}}catch(_){}localStorage.setItem('alin_v99_student_profile',JSON.stringify(p));renderStage();renderEffectiveStore();if(p.phone&&state.schema.student_profiles&&hasSb()){try{await sb.from('student_profiles').upsert({phone:p.phone,name:p.name||null,grade:p.grade||null},{onConflict:'phone'})}catch(_){}}}
  window.v99Reorder=id=>{const o=(db.orders||[]).find(x=>String(x.id)===String(id));if(!o||!o.item_id)return alert('تفاصيل هذا الطلب القديم غير مكتملة');for(let i=0;i<Math.max(1,num(o.qty));i++)if(typeof addToCart==='function')addToCart(o.kind,String(o.item_id));if(typeof openCart==='function')openCart()};
  function renderStudentHub(){const root=$('#v99StudentHub');if(!root)return;let s=null;try{s=typeof currentStudent==='function'?currentStudent():null}catch(_){}const orders=s?(db.orders||[]).filter(o=>o.student_phone===s.phone).slice(0,5):[];if(isDesktop()||isMobile()){if(!s){root.innerHTML='';return}root.innerHTML=`<div class="v99-section-head"><div><h2>طلباتي الأخيرة</h2><small>إعادة الطلب أو متابعة حالته بسهولة</small></div></div><article class="v99-hub-card desktop-orders-card">${orders.map(o=>`<div class="v99-order-row"><div><b>${esc(o.title||o.order_number||o.id)}</b><small>${esc(o.status||'جديد')}${o.ready_eta?` • جاهز تقريباً ${esc(o.ready_eta)}`:''}</small></div><button data-v99-action="reorder" data-id="${esc(o.id)}">أعد الطلب</button></div>`).join('')||'<p>لا توجد طلبات سابقة.</p>'}</article>`;return}const loyalty=(state.tables.loyalty_accounts||[]).find(x=>s&&x.phone===s.phone);root.innerHTML=`<div class="v99-section-head"><div><h2>مساحة الطالب</h2><small>طلباتك ومكافآتك وخيارات الطلب الجماعي</small></div></div><div class="v99-hub-grid"><article class="v99-hub-card"><h3>آخر الطلبات</h3>${s?(orders.map(o=>`<div class="v99-order-row"><div><b>${esc(o.title||o.order_number||o.id)}</b><small>${esc(o.status||'جديد')}${o.ready_eta?` • جاهز تقريباً ${esc(o.ready_eta)}`:''}</small></div><button data-v99-action="reorder" data-id="${esc(o.id)}">أعد الطلب</button></div>`).join('')||'<p>لا توجد طلبات سابقة.</p>'):'<p>سجل دخول الطالب لرؤية طلباتك.</p>'}</article><article class="v99-hub-card"><h3>نقاط آلين</h3>${loyalty?`<div class="v99-price">${fmt(loyalty.points_balance)} نقطة</div><p>يُحتسب الرصيد من النظام الآمن فقط.</p>`:'<div class="v99-notice">لا يوجد رصيد نقاط متاح. تظهر النقاط هنا بعد تفعيل نظام V99 وربط الحساب.</div>'}</article><article class="v99-hub-card"><h3>طلب جماعي</h3><p>اجمع طلبات زملائك في مجموعة واحدة عندما تكون الخدمة مفعلة.</p><button data-v99-action="groupOrder">إنشاء أو انضمام</button></article></div>`}
  function groupOrder(){const ready=state.schema.group_orders&&state.schema.group_order_members;modal(`<h2>الطلب الجماعي</h2>${ready?'<p>أنشئ رمز مجموعة أو أدخل رمزاً موجوداً. يتطلب الحفظ صلاحية قاعدة البيانات.</p>':'<div class="v99-notice error">الخدمة غير مفعلة. طبّق ترحيل V99 أولاً.</div>'}<div class="v99-form"><input id="v99GroupCode" placeholder="رمز المجموعة"><button data-v99-action="groupJoin" ${ready?'':'disabled'}>انضمام للمجموعة</button><button data-v99-action="groupCreate" ${ready?'':'disabled'}>إنشاء مجموعة</button><div id="v99FormMsg"></div></div>`)}
  async function groupWrite(mode){const msg=$('#v99FormMsg'),code=$('#v99GroupCode')?.value.trim().toUpperCase(),s=studentProfile();if(!hasSb()){msg.innerHTML='<div class="v99-notice error">الاتصال غير متاح.</div>';return}try{if(mode==='create'){const c=code||`ALIN-${Math.random().toString(36).slice(2,7).toUpperCase()}`;const {data,error}=await sb.from('group_orders').insert({code:c,status:'open',owner_contact:s.phone||null}).select().single();if(error)throw error;msg.innerHTML=`<div class="v99-notice success">تم إنشاء المجموعة: <b>${esc(data.code)}</b></div>`}else{if(!code)throw Error('اكتب رمز المجموعة');const {data:g,error:e}=await sb.from('group_orders').select('id,code').eq('code',code).eq('status','open').maybeSingle();if(e)throw e;if(!g)throw Error('المجموعة غير موجودة');const {error}=await sb.from('group_order_members').insert({group_order_id:g.id,contact:s.phone||null,name:s.name||null});if(error)throw error;msg.innerHTML='<div class="v99-notice success">تم الانضمام للمجموعة.</div>'}}catch(e){msg.innerHTML=`<div class="v99-notice error">لم يتم الحفظ: ${esc(e.message||'تحقق من الصلاحيات')}</div>`}}
  function updateCountdowns(){$$('[data-deal-end]').forEach(el=>{const end=Date.parse(el.dataset.dealEnd);if(!end){el.textContent='لفترة محدودة';return}const d=Math.max(0,end-now()),h=Math.floor(d/36e5),m=Math.floor((d%36e5)/6e4),s=Math.floor((d%6e4)/1000);el.textContent=d?`ينتهي خلال ${fmt(h)}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:'انتهى العرض'})}
  async function safeTable(name){if(!hasSb())return null;try{const {data,error}=await sb.from(name).select('*').limit(100);if(error)throw error;state.schema[name]=true;return data||[]}catch(_){state.schema[name]=false;return null}}
  async function loadGrowthData(){for(const name of ['student_profiles','bundles','bundle_items','product_reviews','stock_alerts','loyalty_accounts','loyalty_transactions','group_orders','group_order_members','group_order_items']){const x=await safeTable(name);state.tables[name]=x||[]}renderEffectiveStore();renderStudentHub();renderAdminGrowth()}
  function renderAdminGrowth(){const panel=$('#v99AdminPanel');if(panel)panel.remove()}
  window.v99EditMerch=async(kind,id)=>{const x=findItem(kind,id);if(!x)return;const deal=prompt('سعر العرض (اتركه فارغاً للإلغاء)',x.dealPrice||''),start=prompt('بداية العرض ISO أو فارغ',x.dealStart||''),end=prompt('نهاية العرض ISO أو فارغ',x.dealEnd||''),badge=prompt('الشارة',x.badge||''),prep=prompt('دقائق التجهيز',x.prep||'');if([deal,start,end,badge,prep].some(v=>v===null))return;try{await update(kind==='booklet'?'booklets':'products',{deal_price:deal?num(deal):null,deal_start:start||null,deal_end:end||null,badge:badge||null,prep_minutes:prep?num(prep):null},{id});await load();alert('تم حفظ بيانات العرض')}catch(e){alert('تعذر الحفظ. طبّق ترحيل V99 أولاً.\n'+e.message)}};
  function decorateAdminRows(){if(!$('#adminContent'))return;const rows=$$('#adminContent .row');rows.forEach(r=>{if(r.querySelector('[data-v99-merch]'))return;const txt=r.textContent;const x=canonicalItems().find(i=>txt.includes(i.title));if(!x)return;const btn=document.createElement('button');btn.type='button';btn.dataset.v99Merch='1';btn.textContent='عرض V99';btn.onclick=()=>v99EditMerch(x.kind,x.id);(r.querySelector('.row-actions')||r).appendChild(btn)})}
  function setupWrappers(){
    window.addEventListener('alin:data-refreshed',renderStoreStats);
    window.addEventListener('alin:cloud-mutation',event=>{if(['booklets','accounts'].includes(String(event.detail?.table||'')))renderStoreStats()});
    document.addEventListener('alin:cart-changed',()=>{updateDesktopHeader();updateMobileHeader()});
    document.addEventListener('alin:cart-rendered',()=>{
      const close=$('#checkoutModal .x');
      if(close){close.textContent='إغلاق';close.setAttribute('aria-label','إغلاق السلة');close.classList.add(isMobile()?'mobile-cart-close':'desktop-cart-close')}
      updateDesktopHeader();updateMobileHeader();
    });
    document.addEventListener('alin:cart-closed',()=>{
      const close=$('#checkoutModal .x');if(close){close.textContent='×';close.setAttribute('aria-label','إغلاق');close.classList.remove('desktop-cart-close','mobile-cart-close')}
    });
    document.addEventListener('alin:order-created',event=>{
      const items=Array.isArray(event.detail?.items)?event.detail.items:[];
      if(items.length)localStorage.setItem('alin_v99_last_successful_cart',JSON.stringify({at:new Date().toISOString(),items}));
      renderStudentHub();
    });
    const oldTrack=window.trackOrder;if(typeof oldTrack==='function')window.trackOrder=trackOrder=async function(){const r=await oldTrack.apply(this,arguments);const code=$('#trackOrderInput')?.value.trim(),o=(db.orders||[]).find(x=>[x.id,x.order_number,x.tracking_code].map(String).includes(code));if(o&&$('#trackOrderResult')){const extra=[];if(o.ready_eta)extra.push(`الجاهزية المتوقعة: ${o.ready_eta}`);if(o.handoff_token&&['ready','completed'].includes(o.status))extra.push(`<button data-v99-action="handoff" data-id="${esc(o.id)}">رمز الاستلام</button>`);if(extra.length)$('#trackOrderResult').insertAdjacentHTML('beforeend',`<div class="v99-notice">${extra.join('<br>')}</div>`)}return r};
  }
  function handoff(id){const o=(db.orders||[]).find(x=>String(x.id)===String(id));if(!o?.handoff_token)return;modal(`<h2>رمز تسليم الطلب</h2><p>اعرض هذا الرمز للمكتبة. لا يؤكد التسليم وحده؛ التحقق يتم من النظام المصرّح.</p><div class="v99-print-token">${esc(o.handoff_token)}</div><button onclick="window.print()">طباعة الرمز</button>`)}
  function setDesktopFilterDrawer(open,restore=true){if(!isDesktop())return;const root=$('#v99DiscoveryTools'),backdrop=$('.desktop-filter-backdrop'),trigger=$('[data-desktop-control="filter"]');if(!root)return;const wasOpen=root.classList.contains('open');if(open&&!wasOpen){root.dataset.previousHtmlOverflow=document.documentElement.style.overflow||'';document.documentElement.style.overflow='hidden'}else if(!open&&wasOpen){document.documentElement.style.overflow=root.dataset.previousHtmlOverflow||'';delete root.dataset.previousHtmlOverflow}root.classList.toggle('open',open);document.body.classList.toggle('v99-desktop-filter-open',open);trigger?.setAttribute('aria-expanded',String(open));if(backdrop)backdrop.hidden=!open;if(open)requestAnimationFrame(()=>root.querySelector('.v99-drawer-close')?.focus());else if(restore)trigger?.focus()}
  function setMobileFilterDrawer(open,restore=true){if(!isMobile())return;const root=$('#v99DiscoveryTools'),backdrop=$('.mobile-filter-backdrop'),trigger=$('[data-mobile-control="filter"]');if(!root)return;const wasOpen=root.classList.contains('open');if(open&&!wasOpen){root.dataset.previousHtmlOverflow=document.documentElement.style.overflow||'';document.documentElement.style.overflow='hidden'}else if(!open&&wasOpen){document.documentElement.style.overflow=root.dataset.previousHtmlOverflow||'';delete root.dataset.previousHtmlOverflow}root.classList.toggle('open',open);document.body.classList.toggle('v99-mobile-filter-open',open);trigger?.setAttribute('aria-expanded',String(open));if(backdrop)backdrop.hidden=!open;if(open)requestAnimationFrame(()=>root.querySelector('.v99-mobile-drawer-close')?.focus());else if(restore)trigger?.focus()}
  document.addEventListener('click',e=>{if(e.target.classList.contains('v99-modal')){closeModal();return}const b=e.target.closest('[data-v99-action]');if(!b)return;const a=b.dataset.v99Action,x=findItem(b.dataset.kind,b.dataset.id);if(a==='close')closeModal();else if(a==='desktopFavorites')v99ShowFavorites();else if(a==='toggleFilters'){const root=$('#v99DiscoveryTools'),open=root?.classList.toggle('open');b.setAttribute('aria-expanded',String(!!open));if(isDesktop()){document.body.classList.toggle('v99-desktop-filter-open',!!open);const header=$('[data-desktop-control="filter"]');if(header&&header!==b)header.setAttribute('aria-expanded',String(!!open))}const mark=b.querySelector('.v99-toggle-mark');if(mark)mark.textContent=open?'−':'+'}else if(a==='removeFilter'){state.filters[b.dataset.filterKey]=b.dataset.filterKey==='sort'?'recommended':'';syncFilterControls();renderEffectiveStore()}else if(a==='clearFilters'){state.filters={kind:'',grade:'',subject:'',teacher:'',min:'',max:'',available:'',badge:'',sort:'recommended'};syncFilterControls();renderEffectiveStore()}else if(a==='details'&&x)v99OpenDetails(x.kind,x.id);else if(a==='favorite'&&x)v99ToggleFavorite(x.kind,x.id);else if(a==='cart'&&x){if(x.stock!==null&&x.stock<=0)stockForm(x);else if(typeof addToCart==='function')addToCart(x.kind,x.id)}else if(a==='cartQty'&&x){const q=Math.max(1,num($('#v99DetailQty')?.value));for(let i=0;i<q;i++)addToCart(x.kind,x.id);updateDesktopHeader();if(typeof toast==='function')toast('أضيفت الكمية إلى السلة')}else if(a==='buy'&&x){const q=Math.max(1,num($('#v99DetailQty')?.value));for(let i=0;i<q;i++)addToCart(x.kind,x.id);updateDesktopHeader();closeModal(false);openCart()}else if(a==='share'&&x)shareItem(x);else if(a==='stockForm'&&x)stockForm(x);else if(a==='stockSubmit'&&x)stockSubmit(x);else if(a==='reviewForm'&&x)reviewForm(x);else if(a==='reviewSubmit'&&x)reviewSubmit(x);else if(a==='teacher'&&!isDesktop())teacherModal(b.dataset.id);else if(a==='bundle')bundleModal(b.dataset.id);else if(a==='bundleAdd'){addBundle(b.dataset.id);closeModal()}else if(a==='reorder')v99Reorder(b.dataset.id);else if(a==='groupOrder'&&!isDesktop())groupOrder();else if(a==='groupCreate'&&!isDesktop())groupWrite('create');else if(a==='groupJoin'&&!isDesktop())groupWrite('join');else if(a==='handoff')handoff(b.dataset.id)});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&isDesktop()&&$('#v99DiscoveryTools')?.classList.contains('open')){$('#v99DiscoveryTools').classList.remove('open');document.body.classList.remove('v99-desktop-filter-open');const f=$('[data-desktop-control="filter"]');f?.setAttribute('aria-expanded','false');f?.focus();return}if(e.key==='Escape'&&isDesktop()&&!$('#studentAuthModal')?.classList.contains('hidden')){closeStudentAuth();return}const dialog=$('.v99-modal [role="dialog"]');if(!dialog)return;if(e.key==='Escape'){e.preventDefault();closeModal();return}if(e.key!=='Tab')return;const focusable=[...dialog.querySelectorAll('button:not([disabled]),a[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')];if(!focusable.length){e.preventDefault();dialog.focus();return}const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});
  document.addEventListener('change',e=>{if(e.target.matches('[data-filter]')){state.filters[e.target.dataset.filter]=e.target.value;renderEffectiveStore()}if(e.target.id==='v99GradeSelect')saveGrade(e.target.value)});
  document.addEventListener('click',e=>{if(!isDesktop())return;const b=e.target.closest('[data-v99-action]');if(!b)return;const a=b.dataset.v99Action;if(!['desktopFavorites','browseProducts','closeDesktopFilters','toggleFilters'].includes(a))return;e.preventDefault();e.stopImmediatePropagation();if(a==='desktopFavorites')v99ShowFavorites();else if(a==='browseProducts'){closeModal();$('#storeGrid')?.scrollIntoView({behavior:'smooth'})}else if(a==='closeDesktopFilters')setDesktopFilterDrawer(false);else setDesktopFilterDrawer(!$('#v99DiscoveryTools')?.classList.contains('open'))},true);
  document.addEventListener('click',e=>{if(!isDesktop())return;const category=e.target.closest('[data-v99-category]'),clear=e.target.closest('[data-v99-action="clearDesktopCategory"]');if(!category&&!clear)return;e.preventDefault();e.stopImmediatePropagation();if(clear){state.filters.kind='';state.filters.badge=''}else if(category.dataset.v99Category==='deal'){state.filters.kind='';state.filters.badge='deal'}else{state.filters.kind=category.dataset.v99Category;state.filters.badge=''}syncFilterControls();renderEffectiveStore();const heading=$('#v99CatalogHeading');heading?.scrollIntoView({behavior:'smooth',block:'start'});requestAnimationFrame(()=>heading?.focus())},true);
  document.addEventListener('keydown',e=>{if(!isDesktop()||!$('#v99DiscoveryTools')?.classList.contains('open'))return;const root=$('#v99DiscoveryTools');if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();setDesktopFilterDrawer(false);return}if(e.key!=='Tab')return;const focusable=[...root.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')];if(!focusable.length){e.preventDefault();root.focus();return}const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}},true);
  document.addEventListener('click',e=>{if(!isMobile())return;const action=e.target.closest('[data-v99-action]'),category=e.target.closest('[data-v99-category]');if(!action&&!category)return;const a=action?.dataset.v99Action;if(!category&&!['mobileFavorites','browseProducts','toggleMobileFilters','closeMobileFilters','clearMobileCategory'].includes(a))return;e.preventDefault();e.stopImmediatePropagation();if(a==='mobileFavorites')v99ShowFavorites();else if(a==='browseProducts'){closeModal();$('#storeGrid')?.scrollIntoView({behavior:'smooth'})}else if(a==='toggleMobileFilters')setMobileFilterDrawer(!$('#v99DiscoveryTools')?.classList.contains('open'));else if(a==='closeMobileFilters')setMobileFilterDrawer(false);else{if(a==='clearMobileCategory'){state.filters.kind='';state.filters.badge=''}else if(category.dataset.v99Category==='deal'){state.filters.kind='';state.filters.badge='deal'}else{state.filters.kind=category.dataset.v99Category;state.filters.badge=''}syncFilterControls();renderEffectiveStore();const heading=$('#v99MobileCatalogHeading');heading?.scrollIntoView({behavior:'smooth',block:'start'});requestAnimationFrame(()=>heading?.focus())}},true);
  document.addEventListener('keydown',e=>{if(!isMobile()||!$('#v99DiscoveryTools')?.classList.contains('open'))return;const root=$('#v99DiscoveryTools');if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();setMobileFilterDrawer(false);return}if(e.key!=='Tab')return;const focusable=[...root.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])')];if(!focusable.length){e.preventDefault();root.focus();return}const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}},true);
  function init(){setupWrappers();if(window.ALIN_CONFIG?.authEnabled!==true&&(isDesktop()||isMobile())&&typeof openPage==='function')openPage('store');renderFilters();renderStage();renderStore();updateDesktopHeader();updateMobileHeader();loadGrowthData();if(!state.timer)state.timer=setInterval(updateCountdowns,1000);const item=new URLSearchParams(location.search).get('item')||location.hash.replace(/^#item=/,'');if(item){const [kind,...id]=decodeURIComponent(item).split(':');setTimeout(()=>v99OpenDetails(kind,id.join(':')),500)}}
  document.addEventListener('DOMContentLoaded',init,{once:true});
})();


;
