// Alin module: admin/branding.js | v2.0.1
/* ===== admin/js/admin-brand-identity-v176.js ===== */
(function(){
  const defaults={theme:'education',primary:'#0b2345',secondary:'#e1aa32',background:'#f5f7fb',card:'#ffffff',success:'#15803d',warning:'#b7791f',danger:'#b42318',font:'Cairo',radius:18,shadow:'soft'};
  const templates={classic:{primary:'#1d4ed8',secondary:'#f59e0b',background:'#f8fafc',card:'#ffffff',font:'Cairo',radius:16,shadow:'soft'},dark:{primary:'#171717',secondary:'#d4a72c',background:'#f3f4f6',card:'#ffffff',font:'Tajawal',radius:18,shadow:'medium'},education:{primary:'#0b2345',secondary:'#e1aa32',background:'#f5f7fb',card:'#ffffff',font:'Cairo',radius:20,shadow:'soft'}};
  const escv=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const getSettings=()=>{try{return db?.settings||{}}catch(e){return {}}};
  const getStored=()=>{try{return JSON.parse(localStorage.getItem('alin_visual_identity_v176')||'{}')}catch(e){return {}}};
  function current(){const s=getSettings(),l=getStored();return {...defaults,...l,theme:s.visual_theme||l.theme||defaults.theme,primary:s.visual_primary||l.primary||defaults.primary,secondary:s.visual_secondary||l.secondary||defaults.secondary,background:s.visual_background||l.background||defaults.background,card:s.visual_card||l.card||defaults.card,success:s.visual_success||l.success||defaults.success,warning:s.visual_warning||l.warning||defaults.warning,danger:s.visual_danger||l.danger||defaults.danger,font:s.visual_font||l.font||defaults.font,radius:Number(s.visual_radius||l.radius||defaults.radius),shadow:s.visual_shadow||l.shadow||defaults.shadow,logo:s.platform_logo_path||s.platform_logo_url||l.logo||'',logoDark:s.platform_logo_dark_path||l.logoDark||'',icon:s.platform_icon_path||s.platform_icon_url||l.icon||''}}
  const urlOf=p=>{if(!p)return '';if(/^(https?:|data:|blob:)/.test(String(p)))return String(p);try{return typeof mediaUrl==='function'?mediaUrl(p):String(p)}catch(e){return String(p)}};
  async function upload(file,kind){if(!file)return '';if(file.size>3*1024*1024)throw new Error('حجم الصورة يجب أن يكون أقل من 3MB');if(typeof uploadBrandFile==='function')return uploadBrandFile(file,kind);if(typeof uploadFile==='function')return uploadFile('brand/'+kind,file);return await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('تعذر قراءة الصورة'));r.readAsDataURL(file)})}
  function shadowValue(name){return name==='none'?'none':name==='medium'?'0 14px 34px rgba(7,26,55,.11)':'0 8px 24px rgba(7,26,55,.07)'}
  function applyTheme(v){const d=document.documentElement.style;d.setProperty('--alin-primary',v.primary);d.setProperty('--alin-primary-2',v.primary);d.setProperty('--alin-primary-3',v.primary);d.setProperty('--alin-gold',v.secondary);d.setProperty('--alin-gold-2',v.secondary);d.setProperty('--alin-bg',v.background);d.setProperty('--alin-surface',v.card);d.setProperty('--alin-surface-2',v.card);d.setProperty('--alin-success',v.success);d.setProperty('--alin-warning',v.warning);d.setProperty('--alin-danger',v.danger);d.setProperty('--alin-radius-lg',v.radius+'px');d.setProperty('--alin-radius-md',Math.max(10,v.radius-4)+'px');d.setProperty('--alin-shadow-md',shadowValue(v.shadow));document.body.style.fontFamily=`"${v.font}",Tahoma,"Segoe UI",sans-serif`;document.documentElement.dataset.alinTheme=v.theme||'custom';const logo=urlOf(v.logo),icon=urlOf(v.icon);document.querySelectorAll('.alin98-logo,.logo,.brand .logo').forEach(el=>{if(logo){el.innerHTML=`<img src="${escv(logo)}" alt="شعار آلين" style="width:100%;height:100%;object-fit:contain">`} });if(icon)document.querySelectorAll('link[rel="icon"],link[rel="apple-touch-icon"]').forEach(l=>l.href=icon)}
  async function saveOne(k,v){if(typeof settingsSet==='function')return settingsSet(k,String(v));if(typeof alinV57SaveSetting==='function')return alinV57SaveSetting(k,String(v));if(typeof sb!=='undefined'&&sb?.from){const {error}=await sb.from('settings').upsert({key:k,value:String(v)});if(error)throw error;return}try{if(db?.settings)db.settings[k]=String(v);localStorage.setItem('alin_db',JSON.stringify(db))}catch(e){}}
  function previewImage(box,file){if(!file)return;const u=URL.createObjectURL(file);box.innerHTML=`<img src="${u}" alt="معاينة">`}
  function render(root){const v=current();root.className='admin-brand-v176';root.innerHTML=`
    <div class="ab176-head"><div><h2>الهوية البصرية</h2><p>تحكم بألوان وشعار وخط وتصميم منصة آلين من مكان واحد.</p></div><span class="ab176-badge">v2.0.1</span></div>
    <div class="ab176-layout"><div class="ab176-stack">
      <section class="ab176-card"><h3>القوالب الجاهزة</h3><p>اختر قالباً ثم عدّل التفاصيل حسب رغبتك.</p><div class="ab176-templates">
        <button class="ab176-template ${v.theme==='classic'?'active':''}" data-theme="classic"><span class="ab176-swatches"><i style="background:#1d4ed8"></i><i style="background:#f59e0b"></i><i style="background:#f8fafc"></i></span><b>Alin Classic</b><small>أزرق وأبيض</small></button>
        <button class="ab176-template ${v.theme==='dark'?'active':''}" data-theme="dark"><span class="ab176-swatches"><i style="background:#171717"></i><i style="background:#d4a72c"></i><i style="background:#f3f4f6"></i></span><b>Dark Pro</b><small>فحمي وذهبي</small></button>
        <button class="ab176-template ${v.theme==='education'?'active':''}" data-theme="education"><span class="ab176-swatches"><i style="background:#0b2345"></i><i style="background:#e1aa32"></i><i style="background:#f5f7fb"></i></span><b>Education</b><small>هوية آلين التعليمية</small></button>
      </div></section>
      <section class="ab176-card"><h3>الشعار والأيقونة</h3><p>ارفع هوية واضحة بخلفية شفافة، والأيقونة يفضل أن تكون مربعة.</p><div class="ab176-grid">
        <div class="ab176-upload"><div id="ab176LogoPreview" class="ab176-upload-preview">${v.logo?`<img src="${escv(urlOf(v.logo))}" alt="الشعار">`:'آ'}</div><div class="ab176-field"><label>الشعار الأساسي</label><input id="ab176Logo" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml"></div></div>
        <div class="ab176-upload"><div id="ab176DarkLogoPreview" class="ab176-upload-preview">${v.logoDark?`<img src="${escv(urlOf(v.logoDark))}" alt="الشعار الأبيض">`:'آ'}</div><div class="ab176-field"><label>شعار الوضع الداكن</label><input id="ab176DarkLogo" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml"></div></div>
        <div class="ab176-upload full"><div id="ab176IconPreview" class="ab176-upload-preview icon">${v.icon?`<img src="${escv(urlOf(v.icon))}" alt="الأيقونة">`:'آ'}</div><div class="ab176-field"><label>أيقونة التطبيق 512×512</label><input id="ab176Icon" type="file" accept="image/png,image/jpeg,image/webp"></div></div>
      </div></section>
      <section class="ab176-card"><h3>الألوان والخط</h3><p>التغييرات تظهر مباشرة في المعاينة قبل الحفظ.</p><div class="ab176-grid">
        ${[['primary','اللون الأساسي'],['secondary','اللون الثانوي'],['background','الخلفية'],['card','البطاقات'],['success','النجاح'],['warning','التحذير'],['danger','الخطأ']].map(([k,l])=>`<div class="ab176-field"><label>${l}</label><input data-color="${k}" type="color" value="${escv(v[k])}"></div>`).join('')}
        <div class="ab176-field"><label>الخط العربي</label><select id="ab176Font"><option ${v.font==='Cairo'?'selected':''}>Cairo</option><option ${v.font==='Tajawal'?'selected':''}>Tajawal</option><option ${v.font==='IBM Plex Sans Arabic'?'selected':''}>IBM Plex Sans Arabic</option><option ${v.font==='Noto Kufi Arabic'?'selected':''}>Noto Kufi Arabic</option></select></div>
        <div class="ab176-field"><label>الظلال</label><select id="ab176Shadow"><option value="none" ${v.shadow==='none'?'selected':''}>بدون ظل</option><option value="soft" ${v.shadow==='soft'?'selected':''}>خفيف</option><option value="medium" ${v.shadow==='medium'?'selected':''}>متوسط</option></select></div>
        <div class="ab176-field full"><label>استدارة البطاقات والأزرار</label><div class="ab176-slider"><input id="ab176Radius" type="range" min="8" max="30" value="${v.radius}"><output>${v.radius}px</output></div></div>
      </div></section>
      <div class="ab176-actions"><button id="ab176Reset" class="ab176-reset">استعادة الافتراضي</button><button id="ab176Save" class="ab176-save">حفظ وتطبيق الهوية</button></div><div id="ab176Status" class="ab176-status"></div>
    </div><aside class="ab176-preview-wrap"><div class="ab176-card"><h3>معاينة مباشرة</h3><p>نموذج مصغر للمتجر ولوحات المنصة.</p><div id="ab176Preview" class="ab176-preview"><div class="ab176-preview-top"><div class="ab176-preview-brand"><span id="ab176PreviewLogo" class="ab176-preview-logo">آ</span><div><b>منصة آلين</b><small style="display:block;opacity:.75">للملازم والقرطاسية</small></div></div><span>•••</span></div><div class="ab176-preview-body"><div class="ab176-preview-hero"><h4>كل ما تحتاجه للدراسة</h4><p>هوية موحدة وجذابة لكل صفحات المنصة.</p><button>تصفح المتجر</button></div><div class="ab176-preview-cards"><div class="ab176-preview-card"><b>الطلبات</b><small>24 طلباً</small></div><div class="ab176-preview-card"><b>الأرباح</b><small>125,000 د.ع</small></div></div><div class="ab176-preview-note">هذه المعاينة لا تحفظ أي تغيير إلا بعد الضغط على حفظ وتطبيق الهوية.</div></div></div></div></aside></div>`;
    let draft={...v};const sync=()=>{const p=root.querySelector('#ab176Preview');p.style.setProperty('--ab-primary',draft.primary);p.style.setProperty('--ab-secondary',draft.secondary);p.style.setProperty('--ab-bg',draft.background);p.style.setProperty('--ab-card',draft.card);p.style.setProperty('--ab-font',`"${draft.font}",Tahoma,sans-serif`);p.style.setProperty('--ab-radius',draft.radius+'px');p.style.setProperty('--ab-shadow',shadowValue(draft.shadow));root.querySelector('#ab176PreviewLogo').innerHTML=draft.logo?`<img src="${escv(urlOf(draft.logo))}" alt="الشعار">`:'آ'};sync();
    root.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{root.querySelectorAll('[data-theme]').forEach(x=>x.classList.toggle('active',x===b));draft={...draft,...templates[b.dataset.theme],theme:b.dataset.theme};root.querySelectorAll('[data-color]').forEach(i=>i.value=draft[i.dataset.color]);root.querySelector('#ab176Font').value=draft.font;root.querySelector('#ab176Radius').value=draft.radius;root.querySelector('#ab176Radius').nextElementSibling.textContent=draft.radius+'px';root.querySelector('#ab176Shadow').value=draft.shadow;sync()});
    root.querySelectorAll('[data-color]').forEach(i=>i.oninput=()=>{draft[i.dataset.color]=i.value;draft.theme='custom';sync()});root.querySelector('#ab176Font').onchange=e=>{draft.font=e.target.value;sync()};root.querySelector('#ab176Shadow').onchange=e=>{draft.shadow=e.target.value;sync()};root.querySelector('#ab176Radius').oninput=e=>{draft.radius=Number(e.target.value);e.target.nextElementSibling.textContent=draft.radius+'px';sync()};
    const logo=root.querySelector('#ab176Logo'),dark=root.querySelector('#ab176DarkLogo'),icon=root.querySelector('#ab176Icon');logo.onchange=()=>{if(logo.files[0]){previewImage(root.querySelector('#ab176LogoPreview'),logo.files[0]);const u=URL.createObjectURL(logo.files[0]);draft.logo=u;sync()}};dark.onchange=()=>{if(dark.files[0])previewImage(root.querySelector('#ab176DarkLogoPreview'),dark.files[0])};icon.onchange=()=>{if(icon.files[0])previewImage(root.querySelector('#ab176IconPreview'),icon.files[0])};
    root.querySelector('#ab176Reset').onclick=()=>{if(!confirm('استعادة هوية آلین الافتراضية؟'))return;draft={...defaults};render(root)};
    root.querySelector('#ab176Save').onclick=async()=>{const msg=root.querySelector('#ab176Status');msg.className='ab176-status';msg.textContent='جارٍ حفظ الهوية...';try{if(logo.files[0])draft.logo=await upload(logo.files[0],'logo');if(dark.files[0])draft.logoDark=await upload(dark.files[0],'logo-dark');if(icon.files[0])draft.icon=await upload(icon.files[0],'icon');const map={visual_theme:draft.theme,visual_primary:draft.primary,visual_secondary:draft.secondary,visual_background:draft.background,visual_card:draft.card,visual_success:draft.success,visual_warning:draft.warning,visual_danger:draft.danger,visual_font:draft.font,visual_radius:draft.radius,visual_shadow:draft.shadow,platform_logo_path:draft.logo||'',platform_logo_dark_path:draft.logoDark||'',platform_icon_path:draft.icon||''};for(const [k,val] of Object.entries(map))await saveOne(k,val);localStorage.setItem('alin_visual_identity_v176',JSON.stringify(draft));try{if(db?.settings)Object.assign(db.settings,map)}catch(e){}applyTheme(draft);msg.className='ab176-status ok';msg.textContent='تم حفظ وتطبيق الهوية البصرية بنجاح';if(typeof toast==='function')toast('تم تطبيق الهوية البصرية')}catch(e){msg.className='ab176-status err';msg.textContent=e.message||'تعذر حفظ الهوية'}}
  }
  function install(){applyTheme(current());if(window.AlinAdminModules)AlinAdminModules.register('brandIdentity',render);const base=window.adminTab;if(typeof base==='function'&&!base.__brandV176){const w=function(t){if(t==='brandIdentity'){window.activeAdminTab=t;render(document.getElementById('adminContent'));document.querySelectorAll('#adminPage .admin-tabs button').forEach(b=>{const isBrand=(b.getAttribute('onclick')||'').includes("'brandIdentity'");b.classList.toggle('active-admin-tab',isBrand)});return}return base.apply(this,arguments)};w.__brandV176=true;window.adminTab=w}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();window.AlinVisualIdentityV176={apply:()=>applyTheme(current()),render};
})();


;

