// === admin/marketing.js ===
/* ===== admin/js/admin-marketing-v140.js ===== */
(function(){
  let editingBannerId=null, editingCouponId=null;
  const E=v=>typeof esc==='function'?esc(v):String(v??'');
  const M=v=>typeof money==='function'?money(v):Number(v||0).toLocaleString('ar-IQ');
  const D=v=>{if(!v)return 'غير محدد';try{return new Date(v).toLocaleDateString('ar-IQ')}catch(_){return v}};
  const banners=()=>Array.isArray(db?.banners)?db.banners:[];
  const coupons=()=>Array.isArray(v19Coupons)?v19Coupons:[];
  const activeBanner=b=>b.active===true||b.active===1||b.active==='1';
  const couponUsed=c=>Number(c.used_count??c.usage_count??0);
  const couponLimit=c=>Number(c.max_uses??c.usage_limit??0);
  const couponActive=c=>String(c.status||'active')==='active' && (!c.expires_at || new Date(c.expires_at)>=new Date());

  function bannerPreviewSync(){
    const box=document.getElementById('v140BannerPreview');if(!box)return;
    const title=document.getElementById('v140AdTitle')?.value||'عنوان الإعلان';
    const text=document.getElementById('v140AdText')?.value||'سيظهر نص الإعلان هنا';
    const file=document.getElementById('v140AdImage')?.files?.[0];
    box.querySelector('b').textContent=title;box.querySelector('span').textContent=text;
    const old=box.querySelector('img');if(old)old.remove();
    if(file){const img=document.createElement('img');img.src=URL.createObjectURL(file);box.prepend(img)}
  }

  window.renderAdsAdminV140=function(){
    const rows=banners(), active=rows.filter(activeBanner).length;
    adminContent.innerHTML=`<section class="admin-v140"><header class="admin-v140-head"><div><h2>الإعلانات والبنرات</h2><p>إدارة البنرات التي تظهر في المتجر، مع تحديد فترة العرض والرابط وحالة النشر.</p></div><div class="admin-v140-badges"><span class="admin-v140-badge">${rows.length} إعلان</span><span class="admin-v140-badge">${active} نشط</span></div></header><div class="admin-v140-grid"><article class="admin-v140-card"><h3>${editingBannerId?'تعديل الإعلان':'إضافة إعلان جديد'}</h3><div class="admin-v140-preview" id="v140BannerPreview"><div class="admin-v140-preview-copy"><b>عنوان الإعلان</b><span>سيظهر نص الإعلان هنا</span></div></div><form id="v140BannerForm" class="admin-v140-form" onsubmit="return false"><label>عنوان الإعلان<input id="v140AdTitle" required placeholder="مثال: عروض العودة للمدارس" oninput="bannerPreviewSyncV140()"></label><label>النص المختصر<textarea id="v140AdText" placeholder="اكتب وصفاً مختصراً" oninput="bannerPreviewSyncV140()"></textarea></label><label>صورة البنر<input id="v140AdImage" type="file" accept="image/*" onchange="bannerPreviewSyncV140()"></label><label>رابط عند الضغط<input id="v140AdLink" type="url" placeholder="https://..."></label><div class="admin-v140-form-row"><label>بداية العرض<input id="v140AdStart" type="date"></label><label>نهاية العرض<input id="v140AdEnd" type="date"></label></div><label>الحالة<select id="v140AdActive"><option value="1">نشط</option><option value="0">متوقف</option></select></label><div class="admin-v140-actions"><button onclick="saveBannerV140()">${editingBannerId?'حفظ التعديل':'إضافة الإعلان'}</button>${editingBannerId?'<button class="secondary" onclick="cancelBannerEditV140()">إلغاء التعديل</button>':''}</div></form></article><article class="admin-v140-card"><div class="admin-v140-toolbar"><h3>الإعلانات الحالية</h3><input id="v140AdSearch" placeholder="بحث بالعنوان" oninput="filterAdsV140()"></div><div id="v140AdsList" class="admin-v140-list">${bannerRowsHtml(rows)}</div></article></div></section>`;
    if(editingBannerId){const b=rows.find(x=>String(x.id)===String(editingBannerId));if(b){v140AdTitle.value=b.title||'';v140AdText.value=b.text||'';v140AdLink.value=b.link_url||'';v140AdStart.value=(b.start_date||'').slice(0,10);v140AdEnd.value=(b.end_date||'').slice(0,10);v140AdActive.value=activeBanner(b)?'1':'0';bannerPreviewSync()}}
  };
  function bannerRowsHtml(rows){return rows.length?rows.map(b=>`<div class="admin-v140-item" data-search="${E((b.title||'')+' '+(b.text||''))}"><div class="admin-v140-thumb">${b.image_path?`<img src="${E(typeof mediaUrl==='function'?mediaUrl(b.image_path):b.image_path)}" alt="">`:'📣'}</div><div><h4>${E(b.title||'بدون عنوان')}</h4><p>${E(b.text||'')}</p><div class="admin-v140-meta"><span class="admin-v140-pill ${activeBanner(b)?'active':'off'}">${activeBanner(b)?'نشط':'متوقف'}</span><span class="admin-v140-pill">${D(b.start_date)} — ${D(b.end_date)}</span></div></div><div class="admin-v140-item-actions"><button class="secondary" onclick="editBannerV140('${E(b.id)}')">تعديل</button><button onclick="toggleBannerV140('${E(b.id)}',${activeBanner(b)?0:1})">${activeBanner(b)?'إيقاف':'تشغيل'}</button><button class="danger" onclick="deleteBannerV140('${E(b.id)}')">حذف</button></div></div>`).join(''):'<div class="admin-v140-empty">لا توجد إعلانات حتى الآن</div>'}
  window.bannerPreviewSyncV140=bannerPreviewSync;
  window.filterAdsV140=function(){const q=(v140AdSearch.value||'').trim().toLowerCase();document.querySelectorAll('#v140AdsList .admin-v140-item').forEach(x=>x.hidden=!x.dataset.search.toLowerCase().includes(q))};
  window.editBannerV140=id=>{editingBannerId=id;renderAdsAdminV140();adminContent.scrollIntoView({behavior:'smooth'})};
  window.cancelBannerEditV140=()=>{editingBannerId=null;renderAdsAdminV140()};
  window.saveBannerV140=async function(){try{const title=v140AdTitle.value.trim();if(!title)throw Error('اكتب عنوان الإعلان');const file=v140AdImage.files?.[0];let image=null;if(file&&file.name)image=await uploadFile('banners',file,{type:'image'});const payload={title,text:v140AdText.value.trim(),link_url:v140AdLink.value.trim()||null,start_date:v140AdStart.value||null,end_date:v140AdEnd.value||null,active:v140AdActive.value==='1',updated_at:new Date().toISOString()};if(image)payload.image_path=image;if(editingBannerId)await update('banners',payload,{id:editingBannerId});else await insert('banners',{id:uid('AD'),...payload});if(typeof audit==='function')await audit('banner',(editingBannerId?'تعديل':'إضافة')+' إعلان '+title);editingBannerId=null;await load();renderAdsAdminV140();toast('تم حفظ الإعلان')}catch(e){alert(e.message)}};
  window.toggleBannerV140=async(id,on)=>{await update('banners',{active:!!on,updated_at:new Date().toISOString()},{id});await load();renderAdsAdminV140()};
  window.deleteBannerV140=async id=>{if(!confirm('حذف الإعلان نهائياً؟'))return;try{await removeRow('banners',{id});await load();renderAdsAdminV140();toast('تم حذف الإعلان')}catch(e){alert(e.message)}};

  window.renderCouponsAdminV140=function(){
    const rows=coupons(), active=rows.filter(couponActive).length, used=rows.reduce((a,c)=>a+couponUsed(c),0), expired=rows.filter(c=>c.expires_at&&new Date(c.expires_at)<new Date()).length;
    adminContent.innerHTML=`<section class="admin-v140"><header class="admin-v140-head"><div><h2>العروض والكوبونات</h2><p>إنشاء أكواد خصم وتحديد القيمة، عدد الاستخدامات، القسم المستهدف وتاريخ الانتهاء.</p></div></header><div class="admin-v140-stats"><div class="admin-v140-stat"><span>${rows.length}</span><small>إجمالي الكوبونات</small></div><div class="admin-v140-stat"><span>${active}</span><small>نشطة</small></div><div class="admin-v140-stat"><span>${used}</span><small>مرات الاستخدام</small></div><div class="admin-v140-stat"><span>${expired}</span><small>منتهية</small></div></div><div class="admin-v140-grid"><article class="admin-v140-card"><h3>${editingCouponId?'تعديل الكوبون':'إضافة كوبون'}</h3><form class="admin-v140-form" onsubmit="return false"><label>كود الخصم<input id="v140CpCode" placeholder="ALIN20" maxlength="24"></label><div class="admin-v140-form-row"><label>نوع الخصم<select id="v140CpType"><option value="percent">نسبة مئوية</option><option value="fixed">مبلغ ثابت</option></select></label><label>قيمة الخصم<input id="v140CpValue" type="number" min="1"></label></div><div class="admin-v140-form-row"><label>عدد الاستخدامات<input id="v140CpLimit" type="number" min="0" placeholder="0 = بلا حد"></label><label>تاريخ الانتهاء<input id="v140CpExpiry" type="date"></label></div><label>يطبق على<select id="v140CpApplies"><option value="all">كل المتجر</option><option value="booklet">الملازم</option><option value="stationery">القرطاسية</option><option value="gift">الهدايا</option></select></label><label>الحالة<select id="v140CpStatus"><option value="active">نشط</option><option value="disabled">متوقف</option></select></label><div class="admin-v140-actions"><button onclick="saveCouponV140()">${editingCouponId?'حفظ التعديل':'إضافة الكوبون'}</button>${editingCouponId?'<button class="secondary" onclick="cancelCouponEditV140()">إلغاء</button>':''}</div></form></article><article class="admin-v140-card"><div class="admin-v140-toolbar"><h3>قائمة الكوبونات</h3><input id="v140CouponSearch" placeholder="بحث بالكود" oninput="filterCouponsV140()"></div><div id="v140CouponsList" class="admin-v140-list">${couponRowsHtml(rows)}</div></article></div></section>`;
    if(editingCouponId){const c=rows.find(x=>String(x.id)===String(editingCouponId));if(c){v140CpCode.value=c.code||'';v140CpType.value=c.discount_type||'percent';v140CpValue.value=c.discount_value||0;v140CpLimit.value=c.max_uses??c.usage_limit??0;v140CpExpiry.value=(c.expires_at||'').slice(0,10);v140CpApplies.value=c.applies_to||'all';v140CpStatus.value=c.status||'active'}}
  };
  function couponRowsHtml(rows){return rows.length?rows.map(c=>{const limit=couponLimit(c),used=couponUsed(c),active=couponActive(c);return `<div class="admin-v140-item coupon-v140-item" data-search="${E(c.code||'')}"><div><h4 class="coupon-code">${E(c.code)}</h4><p>${c.discount_type==='fixed'?M(c.discount_value)+' د.ع':M(c.discount_value)+'%'} خصم — ${E(c.applies_to||'كل المتجر')}</p><div class="admin-v140-meta"><span class="admin-v140-pill ${active?'active':'off'}">${active?'نشط':'متوقف/منتهي'}</span><span class="admin-v140-pill">استخدام ${used}/${limit||'∞'}</span><span class="admin-v140-pill">ينتهي ${D(c.expires_at)}</span></div></div><div class="admin-v140-item-actions"><button class="coupon-copy" onclick="copyCouponV140('${E(c.code)}')">نسخ</button><button class="secondary" onclick="editCouponV140('${E(c.id)}')">تعديل</button><button onclick="toggleCouponV140('${E(c.id)}','${String(c.status||'active')==='active'?'disabled':'active'}')">${String(c.status||'active')==='active'?'إيقاف':'تشغيل'}</button><button class="danger" onclick="deleteCouponV140('${E(c.id)}')">حذف</button></div></div>`}).join(''):'<div class="admin-v140-empty">لا توجد كوبونات</div>'}
  window.filterCouponsV140=()=>{const q=(v140CouponSearch.value||'').trim().toLowerCase();document.querySelectorAll('#v140CouponsList .admin-v140-item').forEach(x=>x.hidden=!x.dataset.search.toLowerCase().includes(q))};
  window.copyCouponV140=async code=>{try{await navigator.clipboard.writeText(code);toast('تم نسخ الكود')}catch(_){prompt('انسخ الكود',code)}};
  window.editCouponV140=id=>{editingCouponId=id;renderCouponsAdminV140();adminContent.scrollIntoView({behavior:'smooth'})};
  window.cancelCouponEditV140=()=>{editingCouponId=null;renderCouponsAdminV140()};
  window.saveCouponV140=async function(){try{const code=v140CpCode.value.trim().toUpperCase(),value=Number(v140CpValue.value||0);if(!code||value<=0)throw Error('أكمل كود وقيمة الخصم');const payload={code,discount_type:v140CpType.value,discount_value:value,max_uses:Number(v140CpLimit.value||0),usage_limit:Number(v140CpLimit.value||0),expires_at:v140CpExpiry.value?new Date(v140CpExpiry.value+'T23:59:59').toISOString():null,applies_to:v140CpApplies.value,status:v140CpStatus.value};if(editingCouponId)await update('coupons',payload,{id:editingCouponId});else await insert('coupons',{id:uid('CP'),used_count:0,usage_count:0,...payload});if(typeof audit==='function')await audit('coupon',(editingCouponId?'تعديل':'إضافة')+' كوبون '+code);editingCouponId=null;await load();renderCouponsAdminV140();toast('تم حفظ الكوبون')}catch(e){alert(e.message)}};
  window.toggleCouponV140=async(id,status)=>{await update('coupons',{status},{id});await load();renderCouponsAdminV140()};
  window.deleteCouponV140=async id=>{if(!confirm('حذف الكوبون؟'))return;try{await removeRow('coupons',{id});await load();renderCouponsAdminV140();toast('تم حذف الكوبون')}catch(e){alert(e.message)}};

  const oldAdminTab=window.adminTab;
  window.adminTab=function(t){if(t==='ads'){if(typeof markAdminTab==='function')markAdminTab(t);return renderAdsAdminV140()}if(t==='coupons'){if(typeof markAdminTab==='function')markAdminTab(t);return renderCouponsAdminV140()}return oldAdminTab.apply(this,arguments)};
})();


;
